### PR TITLE
WIP Dynamic image tagging using RELEASE_VERSION

### PR DESCRIPTION
**Pull request by sbose78**
needed to work with https://github.com/fabric8io/osio-pipeline
( I'm aware this is similar to https://github.com/thorntail-examples/rest-http/pull/51 , will collate efforts and go for one of these )

### CODE REVIEW

**Review by Ladicek — APPROVED** [review]

**Comment by Ladicek** [comment]
Unlike #51, this makes sense to me.

ok to test

**Comment by Ladicek** [comment]
`Failed: PushImageToRegistryFailed`, hmm...

**Comment by manovotn** [comment]
Log shows internal server error (500), could have been chance.

Retest this please

**Comment by Ladicek** [comment]
The cluster might be misbehaving, let me try once again.

retest this please

**Comment by Ladicek** [comment]
And it of course worked fine now :-/ :-)

**Comment by Ladicek** [comment]
Not gonna merge though, as the title says "WIP".

**Comment by Ladicek** [comment]
AFAIK this no longer applies. If yes, please reopen.

**Pull request closed without merging**
